export const FETCH_STUFF = 'FETCH_STUFF'
export const RECEIVE_STUFF = 'RECEIVE_STUFF'
export const UPDATE_UI = 'UPDATE_UI'
export const UPDATE_UI_MODAL = 'UPDATE_UI_MODAL'
// export const UPDATE_SIDENAV_STATE = 'UPDATE_SIDENAV_STATE']
export const UPDATE_DATA_ON_POST = "UPDATE_DATA_ON_POST"

export const API_CALL_REQUEST = 'API_CALL_REQUEST'
export const API_CALL_SUCCESS = "API_CALL_SUCCESS"
export const API_CALL_FAILURE = 'API_CALL_FAILURE'
